image: ubuntu:14.04

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - apt-get install -qq software-properties-common
  - add-apt-repository ppa:george-edison55/cmake-3.x
  - add-apt-repository ppa:ubuntu-toolchain-r/test
  - apt-get update -qq
  - apt-get upgrade
  - apt-get install -y -qq build-essential clang-3.8 cmake libboost1.55-all-dev libstdc++6 libssl-dev gcc-5 g++-5
  - export CC=clang-3.8
  - export CXX=clang++-3.8

build:
  stage: build
  script: ls && mkdir build && cd build && cmake .. -DBUILD_SSL=YES && make
