before_script:
  - add-apt-repository "deb http://apt.llvm.org/trusty/llvm-toolchain-trusty-4.0 main"
  - add-apt-repository ppa:ubuntu-toolchain-r/test
  - add-apt-repository ppa:george-edison55/precise-backports
  - add-apt-repository ppa:boost-latest/ppa
  - apt-get update -qq
  - apt-get install -y -qq clang-4.0 cmake cmake-data libboost-dev
  - export CC=clang-4.0
  - epxort CXX=clang++-4.0

build:
  stage: build
  script: mkdir build && cd build && cmake .. -DBUILD_SSL=YES && make -j4
