dist: trusty
sudo: false
language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - clang-3.5
            - cmake
            - libboost1.55-all-dev
            - libstdc++6
            - libc6
      env:
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SSL=YES
  - make -j4
