dist: trusty
sudo: false
language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - clang-4.0
            - cmake
            - cmake-data
            - libboost1.55-all-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SSL=YES
  - make -j4